var fs = require('fs');
var dirName = process.argv[2];
fs.mkdirSync("./" + dirName);
process.chdir("./" + dirName); 
fs.mkdirSync('css');
fs.mkdirSync('js');
fs.writeFileSync("./index.html", "<!DOCTYPE><title>Hello</title><h1>Hi</h1><link rel='stylesheet' type='text/css' href='css/style.css'><script src='js/main.js' type='text/javascript' charset='utf-8' async defer></script>");
fs.writeFileSync("css/style.css", "h1{color:red;}");
fs.writeFileSync("./js/main.js", "var string = 'Hello World';alert(string);");
process.exit(0);